### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by Jmrich** [HipsterJazzbo/Landlord#1]
There is a documentation error. Docs say to use "use HipsterJazzbo\LaravelMultiTenant\Traits\BelongsToTenant;" but it returns error because directory doesn't exist. Correct usage based on current directory is "use HipsterJazzbo\Landlord\BelongsToTenant;"

**Comment by Jmrich** [comment]
```'Landlord' => HipsterJazzbo\Landlord\LandlordServiceProvider::class,``` must be added to the alias, and Facade changed to ```return 'HipsterJazzbo\Landlord\Landlord';```

**Comment by HipsterJazzbo** [comment]
Why change the facade class name?

**Comment by Jmrich** [comment]
Only because it originally was as ```return 'HipsterJazzbo\LaravelMultiTenant\TenantScope'``` and that directory doesn't exist

**Comment by HipsterJazzbo** [comment]
Sweet. Fixed that.
