### ISSUE TITLE
Can i replace the tenant id ?

### ISSUE THREAD

**Issue by ricardovigatti** [HipsterJazzbo/Landlord#10]
In my application, i have a permissions called **"elevate-tenant"** that allows an user to select any tenant from the system to be associated with the registry. This permission is usually applied on admin roles.

If i call ```addTenant()``` from a middleware, i will get to replace the tenant calling ```addTenant()``` again or it will create another tenant ?

**Comment by HipsterJazzbo** [comment]
If you call `addTenant()` again with the same `tenant_column`, it'll replace it, yes.
