### ISSUE TITLE
Implicit Binding

### ISSUE THREAD

**Issue by saazrai** [HipsterJazzbo/Landlord#16]
This is a great product. 
But I don't think that this works with Implicit Binding. For eg

Doesn't work
public function show(Lead $lead)
{
    return $lead;
}

This works:
public function show($id)
{
    return Lead::find($id);
}

Kindly check

**Comment by Jmrich** [comment]
I've been using this for quite a while and have always used it how you have it in the first example. You can always use the get tenant method to be sure that the tenant id is set, or run a query debug and see what the output is

**Comment by Jmrich** [comment]
What version of laravel are you using? Had a similar problem and I was on 5.1 and upgraded to 5.2. Found out it wasn't hitting the middleware unless it was in the global stack. Not sure if you are running into the same problem
