### ISSUE TITLE
Eloquent ORM

### ISSUE THREAD

**Issue by bauersfeld** [HipsterJazzbo/Landlord#18]
Great work on Landlord, however, it does not seem to work with ORM relationships. 

My member model has a tenant column called site_id.  I have a another model called Profile that has a relationship to Member, but no site_id.

I'm calling Landlord::addTenant('site_id', $data['siteId']) in my middleware.
  
```php
class Member extends Model
{
    use BelongsToTenant;
}

class Profile extends Model
{
    public function member()
    {
        return $this->hasOne('Models\Member');
    }
}
```

If I tried to find a record using a profile id, the Landlord tenant code does not protect the reference to member.

```php
$profile = Profile::find(1)

$profile->member  // returns the member record regardless of the tenant column set.
```

Am I missing something or is there a way to address this?

**Comment by bauersfeld** [comment]
Problem solved.  Typo on my side.  thx for the great code!

**Comment by tnorthcutt** [comment]
@bauersfeld could you close this since it's a non-issue?
