### ISSUE TITLE
Multiple Tenants in where

### ISSUE THREAD

**Issue by Garogat** [HipsterJazzbo/Landlord#26]
https://github.com/HipsterJazzbo/Landlord/blob/master/src/Landlord.php#L93

here you are adding all tenants with id to the builder and the result should look like:
select * from ... where id=anton and id=lukas

and that cant work?!

I think it should be $builder->orwhere ...

Or am I wrong?

**Comment by warksit** [comment]
I think this is for when you have 2 different tenant columns in which case you would want andWhere. It is not for handling being a member of 2 different tenants which is not supported.

**Comment by HipsterJazzbo** [comment]
What @warksit said is correct. This package is for scoping to a single tenant of any given type.
