### ISSUE TITLE
What is the purpose of the config file?

### ISSUE THREAD

**Issue by eberkund** [HipsterJazzbo/Landlord#29]
In the documentation it says I can set a site wide default tenant column but the `app/landlord.php` file doesn't seem to do anything.

    'default_tenant_columns' => ['tenant_id'],

I still have to specify the `$tenantColumn` in my middleware or anywhere else I want to use it.

    public function handle($request, Closure $next)
    {
        $tenantColumn = 'tenant_id';
        $tenantId = '1';

        Landlord::addTenant($tenantColumn, $tenantId);

        return $next($request);
    }

**Comment by nunomazer** [comment]
The queries builded to select only the tenant records use this config

**Comment by eberkund** [comment]
Could you give an example?

**Comment by seba627** [comment]
no

**Comment by HipsterJazzbo** [comment]
Yeah I can see that'd be confusing. It's used when building the queries that actually do the scoping.
