### ISSUE TITLE
Laravel 5.3

### ISSUE THREAD

**Issue by jlndk** [HipsterJazzbo/Landlord#30]
Hi.

Just started using your package, and I really enjoy it so far!

Since Laravel 5.3 is being released soon (and I'm building a application), I tried to use landlord on the newest beta. However this package is dependent on 5.2.*, and therefore fails to install.
What's the current plan (and potential hurdles) we'll have to overcome to make this compatible with laravel 5.3?

(I have tried to make a local fork and have successfully installed Landlord on 5.3 (by changing the composer.json), but I haven't been able to test the functionality further. I will report back when I get to it.)

**Comment by jlndk** [comment]
Just reporting back with some test results.

Seems like there's no compatibility issues with laravel 5.3 (this may still need more extensive testing). 
If no more issues are found we would only need to bump composer to get this package working on laravel 5.3

**Comment by eberkund** [comment]
Great news

**Comment by nateajohnson** [comment]
I'd really like to use this package but I am using Laravel 5.3. Can we please get the composer version number bumped?

**Comment by john-main-croud** [comment]
+1

**Comment by nateajohnson** [comment]
There is a pull request for this, but it set the lower requirement to 5.3. There's nothing wrong with continuing to allow this to work for 5.2 as well, so if the laravel requirement was something like ~5.2 then I think it would work for all versions 5.2 and higher until 6.0 comes out. Someone should double check that, but I think that would work.

**Comment by nateajohnson** [comment]
Looks like this might be an abandoned project. That's too bad. I pulled the code into my project and it works great. I'd much rather pull it in as a composer dependency, but until it supports Laravel 5.3, that's just not an option for me.

**Comment by john-main-croud** [comment]
I've forked it, adjusted for L5.3 and will maintain it here: https://github.com/CroudSupport/Landlord
Feel free to use it. I'll not be doing any active dev but will happily merge valid pull requests

**Comment by jsphpl** [comment]
An article on the consequences of requiring illuminate/support as a dependency: [http://mattallan.org/2016/dont-use-illuminate-support/](http://mattallan.org/2016/dont-use-illuminate-support/)

**Comment by jbrooksuk** [comment]
This is how we handle `illuminate/support` requirements...

https://github.com/AltThree/Emoji/blob/master/composer.json#L24

**Comment by john-main-croud** [comment]
Yeah that's just a longhand way of saying ~5.1

**Comment by jsphpl** [comment]
Plus it requires the package maintainer to update their package once a new release of support is out, which, in our case obviously didn't happen timely.

**Comment by viviannys** [comment]
@john-main-croud Hi! How can I integrate your fork to my project in laravel 5.3?

**Comment by dschniepp** [comment]
@viviannys add the following code to your composer.json file:

```
{
    ...
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/CroudSupport/Landlord.git"
        }
    ],
    ...
}
```

more on http://stackoverflow.com/a/21678098/1329393

**Comment by eberkund** [comment]
What else do I need for that to work?

Do I then require hipsterjazzbo/landlord or CroudSupport/Landlord?

**Comment by HipsterJazzbo** [comment]
Hey guys. 5.3 support is here today. Sorry about the delay.

**Comment by john-main-croud** [comment]
Can we just confirm that you are planning to maintain this package going forward? Just checking in case I need a contingency plan! :)

**Comment by HipsterJazzbo** [comment]
Absolutely. I use this myself in about fifteen of the services at auraishere.com :)

**Comment by john-main-croud** [comment]
Marvellous :)
