### ISSUE TITLE
TenantModelNotFoundException doesn't get fired

### ISSUE THREAD

**Issue by dennisver** [HipsterJazzbo/Landlord#38]
The TenantModelNotFoundException doesn't fire.
Do I need to catch it somewhere?

If so; where and how?

**Comment by HipsterJazzbo** [comment]
Could you explain more? It fires for me all the time.

**Comment by dennisver** [comment]
It does work, my bad.
It doesn't get fired when you try to access an object which you're not a tenant of. But that makes sense; this exception is about the Model itself, not about an instance of a model.

**Comment by HipsterJazzbo** [comment]
In v2 it's a bit smarter too.
