### ISSUE TITLE
Great Library but how do i implement this for subdomain Tenancy?

### ISSUE THREAD

**Issue by samsoft00** [HipsterJazzbo/Landlord#4]
Hello @HipsterJazzbo, how how do implement this for a subdomain tenancy? Thanks

**Comment by phaberest** [comment]
I'm on the same boat, trying to find out

**Comment by samsoft00** [comment]
@phaberest i ended up using Ruby on rails for my development, hope @HipsterJazzbo  is able to provide this option

**Comment by dlimars** [comment]
@samsoft00 @phaberest i'm developing something with subdomains, check out here https://github.com/dlimars/laravel-tenant-subdomain

**Comment by phaberest** [comment]
Thanks @dlimars , I'll look forward into it :+1: 

By the way I'm getting to the point with something like this
```
        $domain  = str_replace(['http://', 'https://', '//'], '', env('APP_URL'));
        $account = array_shift((explode(".", $_SERVER['HTTP_HOST'])));
        $default = array_shift((explode(".", $domain)));
        if ($account != $default) {
            $managerId = Manager::where('url_part', '=', $account)
                   ->firstOrFail()->id;

            if (!$managerId) {
                abort(404);
            }
            set_meta('manager_url', $account);
            set_meta('manager_id', $managerId);
        }
        set_meta('account::domain', '{account}.'.$domain);
        set_meta('app::url', $domain);
```
in my `AppServiceProvider`

Where `Manager` is Actually my tenant.

Still working on it, but at least it's a solution...

**Comment by HipsterJazzbo** [comment]
Hey guys, I'd do something like this in a middleware:

```php
public function handle($request, Closure $next)
{   
    $pieces = explode('.', $request->getHost());
    $subdomain = $pieces[0];

    // Use the subdomain to get a tenant id somehow
    $tenantId = '';
    Landlord::addTenant('$tenantColumn, $tenantId);

    return $next($request);
}
```

Maybe I'll do up some example middlewares...

**Comment by jcs224** [comment]
Just thought I'd point out, wildcard subdomain route prefixes are supported in Laravel...you could probably use that to forward to the middleware?

https://laravel.com/docs/5.2/routing#route-group-sub-domain-routing

**Comment by phaberest** [comment]
@jcs224 that's actually what my `get_meta('account::domain')` does in routes ;)

**Comment by jcs224** [comment]
@phaberest :+1:
