### ISSUE TITLE
config_path() does not exist in Lumen

### ISSUE THREAD

**Issue by torkiljohnsen** [HipsterJazzbo/Landlord#40]
See service provider:
https://github.com/HipsterJazzbo/Landlord/blob/master/src/LandlordServiceProvider.php

I don't think `config_path()` is available in Lumen at all.

**Comment by anchepiece** [comment]
Maybe something like:
return app()->basePath() . '/config' . ($path ? '/' . $path : $path);
Not sure how other package maintainers do it.

**Comment by rods** [comment]
I think this project is abandoned. Too long for an answer or a fix. The package description says Lumen but it's not compatible at all.

**Comment by HipsterJazzbo** [comment]
This package is most certainly not abandoned, I use it in a dozen projects. Apologies for the delay this month, I've been really sick.

Fixed in v2.0.3 (cf3a456e1d6d4e2f201ddc06cf49415270279f06).
