### ISSUE TITLE
Validation rules not being scoped

### ISSUE THREAD

**Issue by fgilio** [HipsterJazzbo/Landlord#51]
Hi!
Just like the tittle says, validation rules are not being scoped.
This results in errors when, for example, a ```unique``` rule is applied and there is already a same value from another Tenant.

**Comment by HipsterJazzbo** [comment]
Validation rules do not go through Eloquent. If you need to add condition (such as a `team_id`) to your validation, see [the docs](https://laravel.com/docs/5.3/validation#rule-unique) for how to do that.

**Comment by fgilio** [comment]
Yes, that's what I ended up doing. Thanks anyway!
