### ISSUE TITLE
Any plans for Lumen 5.4 ?

### ISSUE THREAD

**Issue by aluferraz** [HipsterJazzbo/Landlord#60]
Hi !

How are you ? Hope you are fine !

It appears that we cannot upgrade to Lumen 5.4 because of Landlord's "illuminate/support 5.2.*" dependecy.. Any plans for supporting Lumen 5.4 ?

Thank you

**Comment by eberkund** [comment]
Same for Laravel 5.4

**Comment by EmadAdly** [comment]
And me also

**Comment by TheDeadCode** [comment]
It was already done. @HipsterJazzbo Needs to force an update to packalyst

**Comment by eberkund** [comment]
Yeah I am using dev-master right now

**Comment by HipsterJazzbo** [comment]
Just kicked it in the pants. Should be fine now :)
