### ISSUE TITLE
Implicit Model Biding with LandLord

### ISSUE THREAD

**Issue by bissolli** [HipsterJazzbo/Landlord#62]
Hey guys!

I started using [implicit model binding](https://laravel.com/docs/5.4/routing#implicit-binding) and LandLord isn't working anymore! I think it is happening because when the model binding do their job I didn't set LandLord tenant yet! Somebody know any trick to do that?

There is how my code works now:

 - My base controller:
```
public function __construct()
    {
        $this->middleware('auth:tenant');
        $this->middleware(function ($request, $next) {
            LandLord::addTenant('tenant_id', auth()->user()->tenant_id);
            return $next($request);
        });
    }
```

 - Method Example
```
public function show(Lead $lead)
    {
        try {
            // It gives the result without filtering my Tenant! 
            // So I can access any tenant's lead!
            return $lead;
        } catch (\Exception $e) {
            return response($e->getMessage(), $e->getCode() || 500);
        }
    }
```

**Comment by lasseal** [comment]
Does the scope apply to no models at all, or just not the `User` (or whatever models extends `Authenticatable`)?

**Comment by patroniton** [comment]
IIRC you need to put the middleware that handles the tenants in the global middleware array in App\Http\Kernel.php (not the routemiddleware array). That way it's handled before any implicit route binding.

**Comment by HipsterJazzbo** [comment]
Yeah, this is by far the most common type of issue for this package, but the answer is: make sure you're adding tenants before you need them :)

**Comment by renanwilliam** [comment]
@HipsterJazzbo Considering that I can't add tenant before the auth (single domain application), how can do it?
