### ISSUE TITLE
Example App Please 

### ISSUE THREAD

**Issue by COLABORATI** [HipsterJazzbo/Landlord#65]
It would be really great to see a small example application for this project to better understand how to implement it the right way, thank you very much!

**Comment by Dmarthaller** [comment]
I would also love to see a small sample application to better understand how to implement this.

**Comment by HipsterJazzbo** [comment]
I'll look into doing that. It might help a lot with understanding the best ways to use it :)

**Comment by Dmarthaller** [comment]
I would love to see a sample application that has a 2 or 3 models with one being a tenant master perhaps Company. 

Thank you for considering this request as I love the idea of being able to use tenancy within Laravel.

**Comment by Dmarthaller** [comment]
Have you had some time to pull together a small sample?

**Comment by tesmojones** [comment]
up

**Comment by tesmojones** [comment]
up

**Comment by javierojeda94** [comment]
up
