### ISSUE TITLE
5.1 Compatibility?

### ISSUE THREAD

**Issue by jcs224** [HipsterJazzbo/Landlord#7]
Since 5.1 is the Long-Term Support version of Laravel, I'm wondering if it would be appropriate to support that as well? What features have been included in 5.2 that aren't in 5.1?

This is a very important concern for LTS-only organizations who don't want to upgrade Laravel every 6-12 months.

**Comment by HipsterJazzbo** [comment]
Well, unfortunately the main reason this library was able to be updated from nightmare hellstew to nice and clean was the new global scope features in 5.2.

**Comment by jcs224** [comment]
Ah, makes sense.
