### ISSUE TITLE
Support for L5.5

### ISSUE THREAD

**Issue by divdax** [HipsterJazzbo/Landlord#71]
Laravel 5.5 is out! 😄 Please update Package!

**Comment by markspolakovs** [comment]
`composer update` in a Laravel 5.5 installation breaks due to Landlord requiring 5.4.

**Comment by divdax** [comment]
@HipsterJazzbo please update dependencies. 😸

**Comment by hakanersu** [comment]
Until the PR merged you can add
```js
"hipsterjazzbo/landlord": "dev-master"
```

```js
"repositories": [
    {
        "type": "vcs",
        "url":  "git@github.com:rikvdlooi/Landlord.git"
    }
]
```
