### ISSUE TITLE
Creating new Tenant scoped Models

### ISSUE THREAD

**Issue by dneykov** [HipsterJazzbo/Landlord#91]
Hi,

creating scoped models is not working properly only saves the tenant_id but not other columns. Here is my example:

```
Language::create([
    'name'=>'bg',
    'locale'=>'bg'
]);
```

If I initialize the model first then is working:
```
$language = new Language();
$language->name = 'bg';
$language->locale = 'bg';
$language->save();
```

**Comment by HelgeSverre** [comment]
Is your fillables configured?

**Comment by dneykov** [comment]
Yes they are but I had stupid typo...

Thanks.

**Comment by HelgeSverre** [comment]
You're welcome :)
